version: "3.3"

services:
  hr-api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: hr-api
    ports:
      - "1900:1900"
    env_file:
      - ../.env
    restart: always
