version: "3.3"

services:
  hr-api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: hr-api
    ports:
      - "3592:3592"
    env_file:
      - ../.env
    restart: always
