version: "3.9"

services:
  hr-api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: hr-api
    ports:
      - "3592:3592"         
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3592/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - ../.env              
    volumes:
      - ../src/uploads:/app/src/uploads   
    restart: always